# Generated by Django 3.2 on 2021-05-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrotomatik', '0002_auto_20210503_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='airinformation',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='earthhumidity',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
