version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=pgpwd

  api_rest:
    build: ./api_rest
    volumes:
      - ./api_rest:/code
    command: "python manage.py runserver 0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./api_rest/.env
    depends_on:
      - db
    restart: always
    environment:
      - PG_HOST=db
